### ISSUE TITLE
Tests fail on clean checked out working directory

### ISSUE THREAD

**Issue by koraktor** [h3rald/glyph#103]
You're last commit (c253c528c4cfce4f3f6db7ee7654806fa1a81e0f) changed the way the testing project directory is deleted.
As I'm not sure way you're only deleting the contents of `test_project` and not the directory itself, I have two suggestions: Either check for the existence of `test_project` before deleting contents or delete the whole directory again.

Otherwise you'll get this error for each test if the directory doesn't exist:
    No such file or directory - /Users/koraktor/open-source/glyph/spec/test_project

**Comment by h3rald** [comment]
Weird! I changed that because I kept getting a getpwd - directory not found error on Linux! On windows it was fine. At the moment, all my tests pass for Ruby 1.8.7, 1.9.1 and JRuby.

I guess I should check for the existence of the directory before deleting it, in that way we should both be happy. What are you testing on? Mac I guess?

**Comment by h3rald** [comment]
Updated block/structure macros (removed newlines/indents).
- Closed by 53aeb95ee62b971810e0ec2f0ec7b1f122456f38.
